### ISSUE TITLE
Exceptions when access view

### ISSUE THREAD

**Issue by zhangchunlin** [limodou/works#1]
```
[ERROR [13152] root 2017-11-07 09:58:34,444 /home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py,891] ('uliweb.contrib.auth.views.login', {}, None)
Traceback (most recent call last):
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1450, in _open
    response = self.call_view(mod, handler_cls, handler, req, res, kwargs=values)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 993, in call_view
    result = self.call_handler(handler, request, response, env, wrap, args, kwargs)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1105, in call_handler
    return wrap(handler, result, request, response, env)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1047, in wrap_result
    response.write(self.template(tmpfile, result, env, default_template=d, layout=layout))
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 834, in template
    return t.generate(vars, env)
  File "/home/zhangclb/oss/uliweb/uliweb/core/template.py", line 616, in generate
    return execute()
  File "index.html", line 262, in _tt_execute
    _tt_tmp = escape(url_for('uliweb.contrib.auth.views.login'))  # layout.html:27 (via bootstrap/bootstrap_layout.html:38, bootstrap/bootstrap_layout.html:20)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 353, in url_for
    return adapter.build(point, values, force_external=_external)
  File "/home/zhangclb/oss/uliweb/uliweb/lib/werkzeug/routing.py", line 1620, in build
    raise BuildError(endpoint, values, method)
BuildError: ('uliweb.contrib.auth.views.login', {}, None)
[INFO] 127.0.0.1 - - [07/Nov/2017 09:58:34] "GET / HTTP/1.1" 500 -
[INFO] 127.0.0.1 - - [07/Nov/2017 09:58:41] "GET /comment HTTP/1.1" 200 -
[ERROR [13152] root 2017-11-07 09:58:49,733 /home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py,891] 'NoneType' object has no attribute 'model_name'
Traceback (most recent call last):
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1428, in _open
    mod, handler_cls, handler = self.prepare_request(req, rule)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 921, in prepare_request
    _klass, mod, handler = self.get_handler(endpoint)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 903, in get_handler
    _klass = handler.im_class()
  File "/home/zhangclb/sandbox/uliweb/works/apps/article/views.py", line 16, in __init__
    self.D = functions.get_model(self.content_type_obj.model_name) #明细表
AttributeError: 'NoneType' object has no attribute 'model_name'
[INFO] 127.0.0.1 - - [07/Nov/2017 09:58:49] "GET /article/add HTTP/1.1" 500 -
[ERROR [13152] root 2017-11-07 09:58:53,472 /home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py,891] 'NoneType' object has no attribute 'model_name'
Traceback (most recent call last):
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1428, in _open
    mod, handler_cls, handler = self.prepare_request(req, rule)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 921, in prepare_request
    _klass, mod, handler = self.get_handler(endpoint)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 903, in get_handler
    _klass = handler.im_class()
  File "/home/zhangclb/sandbox/uliweb/works/apps/article/views.py", line 16, in __init__
    self.D = functions.get_model(self.content_type_obj.model_name) #明细表
AttributeError: 'NoneType' object has no attribute 'model_name'
[INFO] 127.0.0.1 - - [07/Nov/2017 09:58:53] "GET /article HTTP/1.1" 500 -
```

**Comment by limodou** [comment]
Because contenttype table has not been initialized. I've already add dbinit for this. You can try:

```
uliweb dbinit
```

**Comment by zhangchunlin** [comment]
Currently there are still 2 kinds of errors:
```
[INFO]  * Loading DebuggedApplication...
[ERROR [17491] root 2017-11-08 17:26:09,464 /home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py,891] ('uliweb.contrib.auth.views.login', {}, None)
Traceback (most recent call last):
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1450, in _open
    response = self.call_view(mod, handler_cls, handler, req, res, kwargs=values)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 993, in call_view
    result = self.call_handler(handler, request, response, env, wrap, args, kwargs)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1105, in call_handler
    return wrap(handler, result, request, response, env)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1047, in wrap_result
    response.write(self.template(tmpfile, result, env, default_template=d, layout=layout))
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 834, in template
    return t.generate(vars, env)
  File "/home/zhangclb/oss/uliweb/uliweb/core/template.py", line 616, in generate
    return execute()
  File "index.html", line 262, in _tt_execute
    _tt_tmp = escape(url_for('uliweb.contrib.auth.views.login'))  # layout.html:27 (via bootstrap/bootstrap_layout.html:38, bootstrap/bootstrap_layout.html:20)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 353, in url_for
    return adapter.build(point, values, force_external=_external)
  File "/home/zhangclb/oss/uliweb/uliweb/lib/werkzeug/routing.py", line 1620, in build
    raise BuildError(endpoint, values, method)
BuildError: ('uliweb.contrib.auth.views.login', {}, None)
[INFO] 127.0.0.1 - - [08/Nov/2017 17:26:09] "GET / HTTP/1.1" 500 -
[INFO] 127.0.0.1 - - [08/Nov/2017 17:36:38] "GET /develop HTTP/1.1" 200 -
[INFO] 127.0.0.1 - - [08/Nov/2017 17:36:40] "GET /develop/urls HTTP/1.1" 200 -
[INFO] 127.0.0.1 - - [08/Nov/2017 17:36:42] "GET /comment HTTP/1.1" 200 -
[INFO] 127.0.0.1 - - [08/Nov/2017 17:37:01] "GET /article HTTP/1.1" 302 -
[ERROR [17491] root 2017-11-08 17:37:01,333 /home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py,891] global name 'form' is not defined
Traceback (most recent call last):
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1450, in _open
    response = self.call_view(mod, handler_cls, handler, req, res, kwargs=values)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 993, in call_view
    result = self.call_handler(handler, request, response, env, wrap, args, kwargs)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1105, in call_handler
    return wrap(handler, result, request, response, env)
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 1047, in wrap_result
    response.write(self.template(tmpfile, result, env, default_template=d, layout=layout))
  File "/home/zhangclb/oss/uliweb/uliweb/core/SimpleFrame.py", line 834, in template
    return t.generate(vars, env)
  File "/home/zhangclb/oss/uliweb/uliweb/core/template.py", line 616, in generate
    return execute()
  File "login.html", line 217, in _tt_execute
    _tt_tmp = form  # login.html:8 (via bootstrap/bootstrap_layout.html:45)
NameError: global name 'form' is not defined
```

**Comment by zhangchunlin** [comment]
It is OK now, use 'uliweb runserver' not use 'uliweb develop'
